name: API Call at Midnight

on:
  schedule:
    - cron: '0 0 * * *' # This runs the workflow every day at midnight (UTC)
  workflow_dispatch:

jobs:
  api-call:
    runs-on: ubuntu-latest

    steps:
      - name: Make API Call
        run: curl -X DELETE "https://autobook1.vercel.app/api/utils/deletetrashnotes"
