name: Trigger API Endpoint Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API Endpoint
        run: |
          curl -X POST https://notesnook-sand.vercel.app/api/utils/deletetrashnotes \
          -H "Content-Type: application/json"
